name: build
on:
  push:
    branches:
      - main
  #pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    # - uses: actions/checkout@v2  
    # - name: Python Linter
    #   uses: sunnysid3up/python-linter@master
    #   with:
    #     source: "src"
    #     mypy-options: "--ignore-missing-imports --show-error-codes"
    #     pylint-options: "--rcfile=setup.cfg"
    #     isort-options: "-w 100"
    #     django: true      
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        #VALIDATE_ALL_CODEBASE: true
        #VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_PYTHON_ISORT: true
        VALIDATE_PYTHON_PYLINT: true
        VALIDATE_PYTHON_FLAKE8: true
        VALIDATE_HTML: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
